-- CREATE TABLES SQL
-- Kovács Bálit-Hunor
-- Informatika II. D

-- TOTAL TABLES: 27

-- 1. Oldest Music Publisher in the database
SELECT * FROM PUBLISHERS
ORDER BY PUBLISHER_FORMATIONDATE
FETCH FIRST 1 ROW ONLY;

-- 2. Publishers who worked with Kanye West;
SELECT PUBLISHER_NAME "Worked with Kanye" FROM PUBLISHERS
WHERE PUBLISHER_ID  in (
	SELECT PUBLISHER_ID FROM PRODUCERSPUBLISHING
		WHERE PRODUCER_ID = (
		SELECT PRODUCER_ID  FROM PRODUCERS 
		WHERE PRODUCER_NAME LIKE 'Kanye West'));
		
